# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-22 19:19
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='\u6807\u9898')),
                ('synopsis', models.CharField(default='', max_length=200, verbose_name='\u7b80\u4ecb')),
                ('body', DjangoUeditor.models.UEditorField(default='', verbose_name='\u5185\u5bb9')),
                ('commit_nums', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6570')),
                ('author', models.CharField(default='\u8c22\u660a', max_length=20, verbose_name='\u4f5c\u8005')),
                ('author_url', models.URLField(default='', verbose_name='\u4f5c\u8005\u94fe\u63a5')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u7f16\u8f91\u65f6\u95f4')),
                ('click_nums', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6570')),
            ],
            options={
                'verbose_name': '\u535a\u5ba2\u6587\u7ae0',
                'verbose_name_plural': '\u535a\u5ba2\u6587\u7ae0',
            },
        ),
        migrations.CreateModel(
            name='DescComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(default='', max_length=200, verbose_name='\u8bc4\u8bba')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('desc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.BlogsWord', verbose_name='\u6587\u7ae0')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0\u8bc4\u8bba',
                'verbose_name_plural': '\u6587\u7ae0\u8bc4\u8bba',
            },
        ),
        migrations.CreateModel(
            name='Life',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='\u751f\u6d3b')),
            ],
            options={
                'verbose_name': '\u751f\u6d3b',
                'verbose_name_plural': '\u751f\u6d3b',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='\u59d3\u540d')),
                ('content', models.TextField(verbose_name='\u7559\u8a00\u4fe1\u606f')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u7559\u8a00\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7559\u8a00',
                'verbose_name_plural': '\u7559\u8a00',
            },
        ),
    ]
