# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-22 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, verbose_name='\u7528\u6237')),
                ('sex', models.CharField(choices=[('male', '\u7537'), ('female', '\u5973')], default='female', max_length=20, verbose_name='\u6027\u522b')),
                ('province', models.CharField(max_length=128, verbose_name='\u7701\u5e02')),
                ('country', models.CharField(max_length=128, verbose_name='\u56fd\u5bb6')),
                ('city', models.CharField(max_length=128, verbose_name='\u57ce\u5e02')),
                ('headimgurl', models.ImageField(upload_to='menmbers/%Y/%m', verbose_name='\u7528\u6237\u5934\u50cf')),
            ],
            options={
                'verbose_name': '\u6210\u5458',
                'verbose_name_plural': '\u6210\u5458',
            },
        ),
    ]
