# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-22 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='openid',
            field=models.IntegerField(default=0, max_length=30, verbose_name='openid'),
        ),
    ]
