# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-22 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_members_openid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='openid',
            field=models.CharField(default=0, max_length=30, verbose_name='openid'),
        ),
    ]
