# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-23 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_auto_20171022_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='subscribe_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u5173\u6ce8\u65f6\u95f4'),
        ),
    ]
