# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-23 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_members_subscribe_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='subscribe_time',
        ),
        migrations.AddField(
            model_name='members',
            name='address',
            field=models.CharField(default='', max_length=128, verbose_name='\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='members',
            name='company',
            field=models.CharField(default='', max_length=128, verbose_name='\u516c\u53f8'),
        ),
        migrations.AddField(
            model_name='members',
            name='industry',
            field=models.CharField(default='', max_length=128, verbose_name='\u884c\u4e1a'),
        ),
        migrations.AddField(
            model_name='members',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='\u624b\u673a\u53f7'),
        ),
        migrations.AddField(
            model_name='members',
            name='position',
            field=models.CharField(default='', max_length=128, verbose_name='\u804c\u4f4d'),
        ),
        migrations.AddField(
            model_name='members',
            name='realname',
            field=models.CharField(default='', max_length=128, verbose_name='\u771f\u5b9e\u59d3\u540d'),
        ),
    ]
